# config/safety_rules.yaml

# 치료적 안전성 규칙 정의
critical_keywords:
  self_harm:
    - "suicide"
    - "kill myself"
    - "self-harm"
    - "cutting"
    - "ending it all"
    - "not worth living"
    - "want to die"
    - "better off dead"
    - "hurt myself"
    - "end my life"
    - "self-injury"
    - "자살"
    - "죽고 싶다"
    - "자해"
    - "살 가치가 없다"

  violence:
    - "murder"
    - "weapon"
    - "attack"
    - "assault"
    - "hurt others"
    - "violent thoughts"
    - "kill someone"
    - "harm others"
    - "violence"
    - "aggressive"
    - "폭력"
    - "살인"
    - "공격"

  extreme_despair:
    - "hopeless forever"
    - "worthless"
    - "beyond help"
    - "no point in living"
    - "everyone hates me"
    - "completely alone"
    - "nothing matters"
    - "can't go on"
    - "give up everything"
    - "절망적"
    - "아무 의미 없다"
    - "모든 것을 포기"

warning_keywords:
  negative_self_talk:
    - "hate myself"
    - "stupid"
    - "failure"
    - "useless"
    - "pathetic"
    - "disgusting"
    - "worthless"
    - "loser"
    - "nobody"
    - "자기혐오"
    - "바보"
    - "실패자"
    - "쓸모없다"

  isolation:
    - "no one cares"
    - "completely alone"
    - "nobody understands"
    - "invisible"
    - "forgotten"
    - "isolated"
    - "cut off"
    - "disconnected"
    - "아무도 신경 안 써"
    - "완전히 혼자"
    - "아무도 이해 안 해"

  hopelessness:
    - "no hope"
    - "pointless"
    - "meaningless"
    - "stuck forever"
    - "never get better"
    - "can't change"
    - "doomed"
    - "trapped"
    - "희망 없다"
    - "의미 없다"
    - "절대 나아지지 않아"

# 전문가 상담 권유 조건
professional_referral:
  immediate:
    description: "즉시 전문가 상담이 필요한 상황"
    keywords:
      - "suicide"
      - "self-harm"
      - "want to die"
      - "plan to hurt"
      - "ending everything"
      - "kill myself"
      - "자살 계획"
      - "죽고 싶다"
      - "자해하고 싶다"
    action: "emergency_referral"
    message: "당신의 안전이 가장 중요합니다. 지금 즉시 전문가의 도움을 받으시기 바랍니다."
    resources:
      - "National Suicide Prevention Lifeline: 988"
      - "Crisis Text Line: Text HOME to 741741"
      - "생명의전화: 1588-9191"
      - "청소년전화: 1388"

  urgent:
    description: "빠른 시일 내 전문가 상담이 권장되는 상황"
    keywords:
      - "completely hopeless"
      - "can't go on"
      - "breaking down"
      - "losing control"
      - "dangerous thoughts"
      - "overwhelming despair"
      - "절망적"
      - "무너지고 있다"
      - "통제를 잃고 있다"
    action: "urgent_referral"
    message: "현재 상황이 매우 어려우신 것 같습니다. 며칠 내로 전문가와 상담받으시기를 강력히 권합니다."

  recommended:
    description: "전문가 상담이 도움이 될 것으로 판단되는 상황"
    keywords:
      - "struggling for weeks"
      - "can't function"
      - "getting worse"
      - "no support"
      - "crisis building"
      - "몇 주째 힘들다"
      - "기능하지 못한다"
      - "점점 악화"
    action: "general_referral"
    message: "지속적인 어려움을 겪고 계시는군요. 전문가의 도움을 받아보시는 것을 고려해보시기 바랍니다."

# 치료적 품질 지표
therapeutic_quality:
  positive_indicators:
    emotional_support:
      - "support"
      - "understanding"
      - "acceptance"
      - "validation"
      - "comfort"
      - "care"
      - "지지"
      - "이해"
      - "수용"

    growth_orientation:
      - "courage"
      - "growth"
      - "healing"
      - "strength"
      - "resilience"
      - "progress"
      - "용기"
      - "성장"
      - "치유"

    empowerment:
      - "hope"
      - "possibility"
      - "choice"
      - "agency"
      - "power"
      - "control"
      - "희망"
      - "가능성"
      - "선택"

    connection:
      - "together"
      - "supported"
      - "not alone"
      - "community"
      - "belonging"
      - "함께"
      - "지지받는"
      - "혼자가 아닌"

  empathetic_indicators:
    acknowledgment:
      - "understand"
      - "acknowledge"
      - "recognize"
      - "see"
      - "witness"
      - "이해한다"
      - "인정한다"
      - "알아본다"

    validation:
      - "valid"
      - "legitimate"
      - "natural"
      - "human"
      - "understandable"
      - "타당한"
      - "정당한"
      - "자연스러운"

    normalization:
      - "common"
      - "normal"
      - "shared"
      - "universal"
      - "typical"
      - "일반적인"
      - "정상적인"
      - "공통적인"

  safety_indicators:
    protective_language:
      - "safe"
      - "protected"
      - "secure"
      - "held"
      - "supported"
      - "안전한"
      - "보호받는"
      - "안정된"

    non_judgmental:
      - "without judgment"
      - "accepting"
      - "open"
      - "understanding"
      - "비판단적"
      - "수용적"
      - "열린"

# GPT 생성 콘텐츠 특별 검증
gpt_content_validation:
  inappropriate_ai_responses:
    - "as an AI"
    - "I cannot"
    - "I'm not able"
    - "I don't have emotions"
    - "I'm just a language model"
    - "AI 모델로서"
    - "저는 AI이므로"

  template_leakage:
    - "{{"
    - "}}"
    - "[PLACEHOLDER]"
    - "[INSERT"
    - "EXAMPLE_"
    - "템플릿"
    - "예시:"

  coherence_issues:
    - "contradictory"
    - "incoherent"
    - "repeated phrases"
    - "nonsensical"
    - "fragmented"
    - "모순적"
    - "일관성 없는"
    - "의미 불명"

# 콘텐츠 필터링 수준
content_filtering_levels:
  strict:
    description: "가장 엄격한 필터링 (default for therapeutic context)"
    blocks:
      - "all critical keywords"
      - "inappropriate AI responses"
      - "template leakage"
      - "coherence issues"
    allows:
      - "therapeutic processing of difficult emotions"
      - "age-appropriate emotional expression"
      - "growth-oriented language"

  moderate:
    description: "중간 수준 필터링"
    blocks:
      - "critical keywords only"
      - "inappropriate AI responses"
    allows:
      - "honest emotional expression"
      - "some challenging content for processing"

  relaxed:
    description: "최소한의 필터링 (research or development only)"
    blocks:
      - "immediate safety threats only"
    allows:
      - "full range of emotional expression"
      - "research-appropriate content"

# 연령별 안전성 지침
age_specific_guidelines:
  adolescent:
    age_range: "13-17"
    additional_keywords:
      - "school pressure"
      - "peer rejection"
      - "identity crisis"
      - "family conflict"
      - "학교 스트레스"
      - "따돌림"
      - "정체성 혼란"
    messaging_adjustments:
      - "include parent/guardian communication"
      - "school counselor referrals"
      - "age-appropriate resources"

  young_adult:
    age_range: "18-25"
    additional_keywords:
      - "career pressure"
      - "relationship stress"
      - "independence anxiety"
      - "future uncertainty"
      - "취업 스트레스"
      - "인간관계 어려움"
      - "독립에 대한 불안"
    messaging_adjustments:
      - "adult mental health resources"
      - "peer support groups"
      - "career counseling options"

# 문화적 고려사항
cultural_considerations:
  korean_context:
    sensitive_topics:
      - "family honor"
      - "academic pressure"
      - "social conformity"
      - "mental health stigma"
      - "가족의 체면"
      - "학업 압박"
      - "사회적 동조"
      - "정신건강 낙인"
    adapted_messaging:
      - "emphasize confidentiality"
      - "normalize seeking help"
      - "respect family dynamics"
      - "culturally appropriate resources"

# 응급 상황 프로토콜
emergency_protocols:
  immediate_risk:
    triggers:
      - "suicide ideation with plan"
      - "active self-harm intent"
      - "psychotic symptoms"
      - "substance abuse crisis"
    actions:
      - "display emergency resources immediately"
      - "disable further AI interaction"
      - "log incident for review"
      - "provide crisis intervention contacts"

  escalation_pathway:
    level_1: "content warning and therapeutic redirect"
    level_2: "professional referral recommendation"
    level_3: "urgent care referral"
    level_4: "emergency intervention protocol"

# 품질 점수 계산
quality_scoring:
  therapeutic_appropriateness:
    excellent: 90-100
    good: 75-89
    acceptable: 60-74
    concerning: 40-59
    inappropriate: 0-39

  safety_score:
    safe: 80-100
    caution: 60-79
    warning: 40-59
    danger: 0-39

  personalization_quality:
    highly_personalized: 85-100
    well_personalized: 70-84
    moderately_personalized: 55-69
    minimally_personalized: 40-54
    not_personalized: 0-39
